export const projectCard = [
  {
    type: "Domestic",
    name: "EcoHome Rooftop System",
    imgSrc: "/Images/Projects/work-img7.jpg",
    location: "Chennai, India",
    date: "2025",
  },

  {
    type: "Industrial",
    name: "PowerMax Factory Setup",
    imgSrc: "/Images/Projects/work-img6.png",
    location: "Hyderabad, India",
    date: "2024",
  },
  {
    type: "Commercial",
    name: "GreenMall Solar Grid",
    imgSrc: "/Images/Projects/work-img5.jpg",
    location: "Bangalore, India",
    date: "2025",
  },
  {
    type: "Commercial",
    name: "CityOffice Solar Upgrade",
    imgSrc: "/Images/Projects/work-img8.jpg",
    location: "Ahmedabad, India",
    date: "2026",
  },
  {
    type: "Industrial",
    name: "MegaPlant Solar Network",
    imgSrc: "/Images/Projects/work-img9.jpg",
    location: "Surat, India",
    date: "2025",
  },
  {
    type: "Domestic",
    name: "BrightLiving Solar Kit",
    imgSrc: "/Images/Projects/work-img10.jpg",
    location: "Jaipur, India",
    date: "2026",
  },
  {
    type: "Domestic",
    name: "SunSave Home Project",
    imgSrc: "/Images/Home/work-img1.jpg",
    location: "Kolkata, India",
    date: "2024",
  },
  {
    type: "Commercial",
    name: "SmartTrade Solar Solution",
    imgSrc: "/Images/Home/work-img2.jpg",
    location: "Mumbai, India",
    date: "2025",
  },
  {
    type: "Industrial",
    name: "PrimeIndustrial Solar Install",
    imgSrc: "/Images/Home/work-img3.jpg",
    location: "Pune, India",
    date: "2024",
  },
  {
    type: "Domestic",
    name: "SunSave Home Project",
    imgSrc: "/Images/Home/work-img4.jpg",
    location: "Delhi, India",
    date: "2023",
  },
];
